/*
Jeremy Goldstein
Minuteman Library Network

Holdings Profile gathered for annual reports
*/
SELECT
i.location_code AS "Location Code",
l.name AS Location,
COUNT(i.id) FILTER(WHERE i.itype_code_num = 0) AS "(H1) Book",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 1) AS "(H1) Paperback",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 2) AS "(H1) Large Print",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 3) AS "(H1) Reference",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 4) AS "(H1) High Demand Book",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 5) AS "(H1) Speed Read Book",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 6) AS "(H1) Rental Book",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 7) AS "(H1) Reading List",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 8) AS "(H1) Book Plus Computer Disk",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 9) AS "(H1) Literacy",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 10) AS "(*) Periodical",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 11) AS "(H10) Map",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 12) AS "(H1) Score",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 13) AS "(H10) Misc, Pamplet, College Catalog",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 19) AS "(H4) New TV Series",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 20) AS "(H4) TV Series",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 21) AS "(H4) Speed View",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 22) AS "(H4) Speed View TV Series",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 23) AS "(H4) New DVD Feature",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 24) AS "(H4) New VCD Feature",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 25) AS "(H4) VHS Feature",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 26) AS "(H4) VHS Nonfiction",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 27) AS "(H4) DVD Feature",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 28) AS "(H4) DVD Nonfiction",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 29) AS "(H4) VCD Feature",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 30) AS "(H4) VCD Nonfiction",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 31) AS "(H8) Reference CD-ROM",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 32) AS "(H8) Circulating CD-ROM",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 33) AS "(H3) CD Music",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 34) AS "(H3) CD High Demand Music",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 35) AS "(H3) Casette Music",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 36) AS "(H3) CD Spoken Word",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 37) AS "(H3) CD High Demand Spoken Word",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 38) AS "(H3) Cassette Spoken Word",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 39) AS "(H3) Cassette High Demand Spoken Word",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 40) AS "(H3) LP Record",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 41) AS "(H3) Talking Book (for the blind)",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 42) AS "(H8) Software",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 43) AS "(H8) Console Game",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 44) AS "(H10) Film",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 45) AS "(H10) Slides",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 46) AS "(H9) Microfilm",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 47) AS "(H10) Media Kit",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 48) AS "(H10) Game",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 50) AS "(H3) Book on Player",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 51) AS "(H10) eReader",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 52) AS "(H4) VideoOnPlayer",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 100) AS "(H12) YA Book",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 101) AS "(H12) YA Paperback",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 102) AS "(H12) YA Large Print",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 103) AS "(H12) YA Reference Book",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 104) AS "(H12) YA High Demand Book",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 105) AS "(H12) YA Reading List",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 106) AS "(H12) YA YA Book Plus Computer Disk",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 107) AS "(*) YA Magazine",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 108) AS "(H21) YA Miscellaneous",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 109) AS "(H12) YA Speed Read",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 112) AS "() YA 112",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 113) AS "() YA 113",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 114) AS "() YA 114",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 115) AS "() YA 115",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 116) AS "() YA 116",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 117) AS "() YA 117",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 118) AS "() YA 118",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 119) AS "() YA 119",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 120) AS "() YA 120",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 121) AS "() YA 121",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 122) AS "() YA 122",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 123) AS "() YA 123",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 124) AS "() YA 124",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 125) AS "() YA 125",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 126) AS "() YA 126",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 127) AS "() YA 127",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 128) AS "() YA 128",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 129) AS "() YA 129",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 130) AS "() YA 130",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 131) AS "() YA 131",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 132) AS "() YA 132",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 133) AS "() YA 133",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 150) AS "() 150",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 151) AS "() 151",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 152) AS "() 152",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 153) AS "() 153",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 154) AS "() 154",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 155) AS "() 155",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 156) AS "() 156",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 157) AS "() 157",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 158) AS "() 158",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 159) AS "() 159",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 160) AS "() 160",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 163) AS "() 163",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 164) AS "() 164",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 165) AS "() 165",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 166) AS "() 166",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 167) AS "() 167",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 168) AS "() 168",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 169) AS "() 169",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 170) AS "() 170",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 171) AS "() 171",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 172) AS "() 172",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 173) AS "() 173",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 174) AS "() 174",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 175) AS "() 175",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 176) AS "() 176",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 177) AS "() 177",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 178) AS "() 178",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 179) AS "() 179",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 180) AS "() 180",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 181) AS "() 181",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 182) AS "() 182",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 183) AS "() 183",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 221) AS "() 221",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 222) AS "() 222",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 223) AS "() 223",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 224) AS "() 224",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 239) AS "() 239",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 240) AS "() 240",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 241) AS "() 241",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 242) AS "() 242",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 243) AS "() 243",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 244) AS "() 244",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 245) AS "() 245",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 246) AS "() 246",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 247) AS "() 247",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 248) AS "() 248",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 249) AS "() 249",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 250) AS "() 250",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 251) AS "() 251",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 252) AS "() 252",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 253) AS "() 253",
COUNT(i.id) FILTER(WHERE i.itype_code_num = 255) AS "() 255"


FROM
sierra_view.item_record as i
JOIN
sierra_view.location_myuser l
ON
i.location_code = l.code

GROUP BY
1,2
ORDER BY
1

